services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  load-balancer:
    build:
      context: .
      dockerfile: packages/loadbalancer/Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  collaborative-room1:
    build:
      context: .
      dockerfile: packages/collaborative/Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  collaborative-room2:
    build:
      context: .
      dockerfile: packages/collaborative/Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    restart: unless-stopped
    networks:
      - app-network
